// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.batch.annotations;

import com.bfds.saec.batch.annotations.RangeVo;

privileged aspect RangeVo_Roo_JavaBean {
    
    public String RangeVo.getValue() {
        return this.value;
    }
    
    public String RangeVo.getPropertyName() {
        return this.propertyName;
    }
    
}
