// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.scheduling.domain;

import com.bfds.scheduling.domain.JobConfig;
import com.bfds.scheduling.domain.JobConfigDataOnDemand;
import com.bfds.scheduling.domain.JobConfigIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JobConfigIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JobConfigIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JobConfigIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JobConfigIntegrationTest: @Transactional;
    
    @Autowired
    private JobConfigDataOnDemand JobConfigIntegrationTest.dod;
    
    @Test
    public void JobConfigIntegrationTest.testCountJobConfigs() {
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to initialize correctly", dod.getRandomJobConfig());
        long count = JobConfig.countJobConfigs();
        Assert.assertTrue("Counter for 'JobConfig' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JobConfigIntegrationTest.testFindJobConfig() {
        JobConfig obj = dod.getRandomJobConfig();
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to provide an identifier", id);
        obj = JobConfig.findJobConfig(id);
        Assert.assertNotNull("Find method for 'JobConfig' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JobConfig' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JobConfigIntegrationTest.testFindAllJobConfigs() {
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to initialize correctly", dod.getRandomJobConfig());
        long count = JobConfig.countJobConfigs();
        Assert.assertTrue("Too expensive to perform a find all test for 'JobConfig', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JobConfig> result = JobConfig.findAllJobConfigs();
        Assert.assertNotNull("Find all method for 'JobConfig' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JobConfig' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JobConfigIntegrationTest.testFindJobConfigEntries() {
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to initialize correctly", dod.getRandomJobConfig());
        long count = JobConfig.countJobConfigs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JobConfig> result = JobConfig.findJobConfigEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JobConfig' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JobConfig' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JobConfigIntegrationTest.testFlush() {
        JobConfig obj = dod.getRandomJobConfig();
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to provide an identifier", id);
        obj = JobConfig.findJobConfig(id);
        Assert.assertNotNull("Find method for 'JobConfig' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJobConfig(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JobConfig' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JobConfigIntegrationTest.testMergeUpdate() {
        JobConfig obj = dod.getRandomJobConfig();
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to provide an identifier", id);
        obj = JobConfig.findJobConfig(id);
        boolean modified =  dod.modifyJobConfig(obj);
        Integer currentVersion = obj.getVersion();
        JobConfig merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JobConfig' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JobConfigIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to initialize correctly", dod.getRandomJobConfig());
        JobConfig obj = dod.getNewTransientJobConfig(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JobConfig' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'JobConfig' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JobConfigIntegrationTest.testRemove() {
        JobConfig obj = dod.getRandomJobConfig();
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobConfig' failed to provide an identifier", id);
        obj = JobConfig.findJobConfig(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JobConfig' with identifier '" + id + "'", JobConfig.findJobConfig(id));
    }
    
}
