// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.batch.file.domain;

import com.bfds.saec.batch.file.domain.VendorConfig;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VendorConfig_Roo_Configurable {
    
    declare @type: VendorConfig: @Configurable;
    
}
