// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.validation.message;

import com.bfds.validation.message.Message;
import java.util.Date;
import org.springframework.binding.message.Severity;

privileged aspect Message_Roo_JavaBean {
    
    public String Message.getSource() {
        return this.source;
    }
    
    public String Message.getText() {
        return this.text;
    }
    
    public Severity Message.getSeverity() {
        return this.severity;
    }
    
    public Date Message.getCreatedOn() {
        return this.createdOn;
    }
    
}
