// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.scheduling.domain;

import com.bfds.scheduling.domain.MailingList;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MailingList_Roo_Configurable {
    
    declare @type: MailingList: @Configurable;
    
}
