// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.validation.message;

import com.bfds.validation.message.MessageIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MessageIntegrationTest_Roo_Configurable {
    
    declare @type: MessageIntegrationTest: @Configurable;
    
}
